[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = [
  "cd ../.. && cd packages/shared && npm install && npm run build",
  "cd ../../apps/api && npm install",
  "cd ../../apps/api && npm link ../../packages/shared"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
