[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "cd ../.. && cd packages/shared && npm install && npm run build",
  "npm install",
  "npm link ../../packages/shared"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
